packages:
  - 'apps/web'
  - 'apps/studio'
  - 'apps/admin'
  - 'apps/functions'
  - 'packages/*'

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  esbuild: true
